### ISSUE TITLE
blacklist instead of whitelist

### ISSUE THREAD

**Issue by mrpond** [abba23/spotify-adblock-linux#48]
Hi, I make bts on windows,
this is how I implement ads banner blocked 
https://github.com/mrpond/BlockTheSpot/blob/f16783f41f277964359e31fa304715801b8fc6be/src/hosts.cpp#L9

**Comment by abba23** [comment]
I think there are advantages and disadvantages to using a whitelist. On the one hand, not having a whitelist means less maintenance effort and simpler program logic. On the other hand, having to explicitly whitelist new domains means that ads are less likely to go through when there are changes on Spotify's end and you're also blocking other potentially unwanted connections like third party trackers by default.

Using a whitelist initially seemed like a good idea, because the list was very short and didn't have to be changed very often. I didn't expect Spotify to stream podcasts directly from third parties in some regions though. So if that turns out to be a bigger problem, switching to just using a blacklist might be an option.

**Comment by mrpond** [comment]
currently ads banner are only fetch from adservice.google.xxx and *.doubleclick.net
I approach white-list/adguard dns look up long ago. only these 2 above domain serv banner.
