### ISSUE TITLE
still gettin ads

### ISSUE THREAD

**Issue by katokatoi** [abba23/spotify-adblock-linux#5]
still gettin ads, installed thru AUR 

http://aur.archlinux.org/packages/spotify-adblock-git

**Comment by abba23** [comment]
How did you start Spotify? You can't just run `spotify` from the terminal or use the original launcher ("Spotify") that comes with the Spotify package.

In order to load the adblocking library file, you have to run it from a terminal using `LD_PRELOAD=/usr/lib/spotify-adblock.so spotify` or use the new launcher ("Spotify (adblock)"), which is created during the AUR package's installation.

**Comment by katokatoi** [comment]
it was an issue on my side, pamac had some weird shhhh....ugar goin on and didn't do its job properly. cleared cache, reinstalled lightdm uninstalled corrupted packages and installed spotify+adblocker again. it works now. my bad. so sorry to have bothered you
