### ISSUE TITLE
Doesnt work on the new version

### ISSUE THREAD

**Issue by muametgrooby** [abba23/spotify-adblock-linux#76]
After updating spotify, it doesnt work anymore.

**Comment by abba23** [comment]
People can't help you with your problem if they don't know what that problem is.

* What exactly doesn't work? (Does Spotify not start?, Does it not play songs?, Are ads not blocked?)
* Which Spotify version did you update to?
* Which adblocker version/commit do you use?
* Were there any errors during compilation?
* When running Spotify with the adblocker, is there any output in the terminal?

**Comment by muametgrooby** [comment]
I downgraded to the previous version and it works now, the adblocker was not working.
