### ISSUE TITLE
"sudo make install" fails

### ISSUE THREAD

**Issue by Robzyy** [abba23/spotify-adblock-linux#84]
As the title says: running "sudo make install" fails. This is the outputted data:
```install --strip -Dm644 -t /usr/local/lib spotify-adblock.so
strip: /usr/local/lib/spotify-adblock.so: file format not recognized
install: strip process terminated abnormally
make: *** [Makefile:19: install] Error 1
```
Note that simply running "make" returns 
```make: Nothing to be done for 'all'.```
and i don't think that should be the expected result. 

N.B.: everything else seemed to work flawlessly

**Comment by abba23** [comment]
This might be the same problem as #41. For some reason gcc sometimes produces a corrupt output for some people. Please try compiling it again.

>Note that simply running "make" returns `make: Nothing to be done for 'all'.`

Make doesn't do anything when you try to compile again without having made any changed to the source code, because that would usually be a waste of time. You should run `make clean` to delete the corrupt file before running `make` again.

**Comment by Robzyy** [comment]
Yeah, I just got the error 3 times in a row before opening the issue, I guess it's wasn't my lucky day, but it seems to be fixed now, thanks!
