### ISSUE TITLE
Adblock sometimes work and other times don't

### ISSUE THREAD

**Issue by harrwester** [abba23/spotify-adblock-linux#94]
I've installed spotify from flatpak and run the adblock as .desktop from menu shortcut on LM20. When I used spotify-adblock for the first time 2 days ago, it seemed to work well (even when I skipped dozens of songs) at least until I put the PC to sleep. The next day I got ads every now and then (or at least it was my feeling). Today, no matter how many times I run the adblock, I got plenty of ads. Is there a procedure to it or when to run it (f.e. always after startup, sleep, before/after login to spotify, etc.)? Does VPN affect the adblock? Or does the adblock just reduce the number of ads?

**Comment by abba23** [comment]
>I've installed spotify from flatpak

It likely doesn't work with the Flatpak version at all (see #55). Please try installing it instead using the instructions at the bottom of [this page](https://www.spotify.com/us/download/linux).

>When I used spotify-adblock for the first time 2 days ago, it seemed to work well

Probably just a coincidence due to Spotify ads appearing at irregular intervals. There have been multiple issues here with people claiming to see fewer ads or only audio ads and it turning out that the adblocker wasn't loaded.

>Does VPN affect the adblock? 

No, a VPN shouldn't affect it.

>does the adblock just reduce the number of ads?

No, all the ads should be completely gone if everything works correctly.

**Comment by harrwester** [comment]
Alright, because I had it installed through software manager as flatpak (there's also a snap in there) since you mentioned in notes that it won't work with snap. So I uninstalled the flatpak and got it from https://www.spotify.com/us/download/linux/ as a debian package and now it seems to work flawlessly, at least for few couple of hours. Maybe it'd be helpful for others (and newbies like myself) to mention this in notes as well.
