### ISSUE TITLE
curl/curl.h: No such file or directory

### ISSUE THREAD

**Issue by TheGlitchh** [abba23/spotify-adblock-linux#99]
it seems the make command doesn't hold  as we need curl-devel 

fix : ```sudo apt-get install libcurl4-gnutls-dev```

error and fix are shown in the screenshot
![Screenshot from 2021-02-02 21-54-43](https://user-images.githubusercontent.com/66838685/106629923-5713fd80-65a1-11eb-9413-0f63b1bdab6a.png)

**Comment by abba23** [comment]
I'm guessing you're trying to build the latest release using the instructions from the latest commit (because that's what Github shows by default). The curl dependency has since been removed after that release was made. If you look at the readme from when the release was made (e.g. by selecting the corresponding tag on Github or opening the file in the directory you cloned), you should see the curl dependency being mentioned.

**Comment by TheGlitchh** [comment]
but people won't do that right ? so if you mention this in your latest build it will be great for some people who just want to use your adblocker and get on with their life
